### ISSUE TITLE
2021 - есть ли изменения в Вашем подходе ?

### ISSUE THREAD

**Issue by gayratv** [xnimorz/frontend-conf-materials#1]
Никита, В 2021 году с удвольствием просмотрел Ваш доклад, большое Вам спасибо:
https://youtu.be/tV76RapGubo

Скажите пожалуйста, изменился ли Ваш подход к обработке бизнес логики в 2021 году?
В цонце доклада Вы сказали что решили отказаться от Redux Saga для того чтобы снизить порог входа для разработчиков.

Используете ли Вы сейчас Вашу методику - или Вы внесли в нее некоторые улучшения?

**Comment by xnimorz** [comment]
Приветствую @Ulibka68 
Извиняюсь, давно не заходил, не видел. 

Да, я бы сказал, доклад морально заметно устарел. 

Я бы рекомендовал смотреть в сторону effector или logux/store. 

Причин этому несколько. Из основных
1) размер бандла - подход в докладе (да и в целом почти все redux-based решения) не tree-shakable
2) удобство зависимостей - явные зависимости через импорты > неявные через строки

**Comment by gayratv** [comment]
Большое спасибо за Ваше мнение!
